version: '3.4'

services:
  proposta-service:
    build: ./src/PropostaService.Api
    ports:
      - "5001:80"
    depends_on:
      - proposta-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - seguros-net

  contratacao-service:
    build:
      context: ./src/ContratacaoService.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
    depends_on:
      - contratacao-db
    networks:
      - seguros-net

  proposta-db:
    image: postgres:15
    container_name: proposta-db
    environment:
      POSTGRES_DB: propostas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - seguros-net

  proposta-db-prod:
    image: postgres:15
    container_name: proposta-db-prod
    environment:
      POSTGRES_DB: propostas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5434:5432"
    networks:
      - seguros-net

networks:
  seguros-net:
